services:
  - type: web
    name: whisperdnd
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 8080
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
